# Yarn Berry configuration
# This ensures consistent Yarn 4.x behavior across all environments

nodeLinker: node-modules

# Enable zero-install for faster CI builds (optional - comment out if not needed)
# enableGlobalCache: false
